### ISSUE TITLE
The following section does not work

### ISSUE THREAD

**Issue by MrBlasyMSK** [superbobby2000/VanishV2#57]
```yml
can-send-msg: true
messages:
  sender-error: "§fNo se ha encontrado ese jugador"
  receiver-message: "§c%sender intentó enviarte un mensaje: §7%message"
  ```
  
I have also added the vanish.see permission to the Guest range (which is the current one I have) and it still doesn't work, I don't know if it's a PurePerms problem.
